require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AnalisesController do

  # This should return the minimal set of attributes required to create a valid
  # Analise. As you add validations to Analise, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "titulo" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AnalisesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  # note que nao estou testando quando o usuario nao esta logado ou nao e um admin
  # TODO criar mais testes alem do basico
  before :each do
  	@user = FactoryGirl.build(:user, admin: true)
    AnalisesController.any_instance.stub(:current_user).and_return @user
  end

  describe "GET index" do
    it "assigns all analises as @analises" do
      analise = Analise.create! valid_attributes
      get :index, {}, valid_session
      assigns(:analises).should eq([analise])
    end
  end

  describe "GET show" do
    it "assigns the requested analise as @analise" do
      analise = Analise.create! valid_attributes
      get :show, {:id => analise.to_param}, valid_session
      assigns(:analise).should eq(analise)
    end
  end

  describe "GET new" do
    it "assigns a new analise as @analise" do
    	fornecedor = FactoryGirl.create(:fornecedor, id: 1)
      get :new, {:fornecedor_id => "1"}, valid_session
      assigns(:analise).should be_a_new(Analise)
    end
  end

  describe "GET edit" do
    it "assigns the requested analise as @analise" do
      analise = Analise.create! valid_attributes
      get :edit, {:id => analise.to_param}, valid_session
      assigns(:analise).should eq(analise)
    end
  end

  describe "POST create" do
  	before :each do
    	@fornecedor = FactoryGirl.create(:fornecedor, id: 1)
  	end
    describe "with valid params" do
      it "creates a new Analise" do
        expect {
          post :create, {:analise => valid_attributes, :fornecedor_id => "1"}, valid_session
        }.to change(Analise, :count).by(1)
      end

      it "assigns a newly created analise as @analise" do
        post :create, {:analise => valid_attributes, :fornecedor_id => "1"}, valid_session
        assigns(:analise).should be_a(Analise)
        assigns(:analise).should be_persisted
      end

      it "redirects to the created analise" do
        post :create, {:analise => valid_attributes, :fornecedor_id => "1"}, valid_session
        response.should redirect_to(Analise.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved analise as @analise" do
        # Trigger the behavior that occurs when invalid params are submitted
        Analise.any_instance.stub(:save).and_return(false)
        post :create, {:analise => { "titulo" => "invalid value" }, :fornecedor_id => "1"}, valid_session
        assigns(:analise).should be_a_new(Analise)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Analise.any_instance.stub(:save).and_return(false)
        post :create, {:analise => { "titulo" => "invalid value" }, :fornecedor_id => "1"}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested analise" do
        analise = Analise.create! valid_attributes
        # Assuming there are no other analises in the database, this
        # specifies that the Analise created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Analise.any_instance.should_receive(:update_attributes).with({ "titulo" => "MyString" })
        put :update, {:id => analise.to_param, :analise => { "titulo" => "MyString" }}, valid_session
      end

      it "assigns the requested analise as @analise" do
        analise = Analise.create! valid_attributes
        put :update, {:id => analise.to_param, :analise => valid_attributes}, valid_session
        assigns(:analise).should eq(analise)
      end

      it "redirects to the analise" do
        analise = Analise.create! valid_attributes
        put :update, {:id => analise.to_param, :analise => valid_attributes}, valid_session
        response.should redirect_to(analise)
      end
    end

    describe "with invalid params" do
      it "assigns the analise as @analise" do
        analise = Analise.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Analise.any_instance.stub(:save).and_return(false)
        put :update, {:id => analise.to_param, :analise => { "titulo" => "invalid value" }}, valid_session
        assigns(:analise).should eq(analise)
      end

      it "re-renders the 'edit' template" do
        analise = Analise.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Analise.any_instance.stub(:save).and_return(false)
        put :update, {:id => analise.to_param, :analise => { "titulo" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested analise" do
      analise = Analise.create! valid_attributes
      expect {
        delete :destroy, {:id => analise.to_param}, valid_session
      }.to change(Analise, :count).by(-1)
    end

    it "redirects to the analises list" do
      analise = Analise.create! valid_attributes
      delete :destroy, {:id => analise.to_param}, valid_session
      response.should redirect_to(analises_url)
    end
  end

end
